// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vgzqpsskryaygkggvfqq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZnenFwc3NrcnlheWdrZ2d2ZnFxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3OTU1MTUsImV4cCI6MjA2MDM3MTUxNX0.lDiHeToIk7dI3viCxyJyDzUoA4ekQpvz-9joBLqqG_E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);